# Workflow to test the ServerConfig class
name: Testbed - ServerConfig
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
    - '.github/workflows/TEST_ServerConfig.yml'
    - '.github/actions/test_config/**'
    - 'tests/cases/configs/t_ServerConfig.py'
    - 'tests/config/**'
    - 'requirements.txt'

jobs:

  run_testbed_server_config:
    name: Run ServerConfig Testbed
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-ServerConfig
      cancel-in-progress: true

    steps:
  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get Dependencies
      uses: opengamedata/setup-ogd-py-dependencies@v1.0
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}
    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          verbose_output:     "True"
          with_server_config: "True"

  # 2. Build & configure remote environments

  # 3. Perform export
    - name: Execute testbed
      run: python -m unittest discover -s tests/cases/configs -p "t_*.py" -t ./

  # 4. Cleanup & complete
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "test-log"
        path: ./*.log
